CREATE TABLE "DBO"."JOBPROPERTY"  (
                  "ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
                    START WITH +1  
                    INCREMENT BY +1  
                    MINVALUE +1  
                    MAXVALUE +2147483647  
                    NO CYCLE  
                    CACHE 20  
                    NO ORDER ) , 
                  "SCHEDULETYPE" VARCHAR(50) NOT NULL , 
                  "JOBTYPE" VARCHAR(20) , 
                  "JOBNAME" VARCHAR(50) NOT NULL , 
                  "X" DECIMAL(18,6) , 
                  "Y" DECIMAL(18,6) , 
                  "ISVALID" INTEGER , 
                  "ISSCHEDULE" INTEGER , 
                  "ON_FAIL_ACTION" VARCHAR(10) , 
                  "COST" TIME , 
                  "GROUPID" INTEGER , 
                  "GROUPNAME" VARCHAR(128) , 
                  "MEMO" VARCHAR(128) , 
                  "PARAMS" VARCHAR(1000) , 
                  "INSERTTIME" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
                  "UPDATETIME" TIMESTAMP )   
                 IN "DWSPACE" INDEX IN "DWIDXSPACE" ; 


-- DDL Statements for primary key on Table "DBO"."JOBPROPERTY"

ALTER TABLE "DBO"."JOBPROPERTY" 
        ADD PRIMARY KEY
                ("SCHEDULETYPE",
                 "JOBNAME");

CREATE TABLE "DBO"."JOBWAITINGPOOL"  (
                  "ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
                    START WITH +1  
                    INCREMENT BY +1  
                    MINVALUE +1  
                    MAXVALUE +2147483647  
                    NO CYCLE  
                    CACHE 20  
                    NO ORDER ) , 
                  "SCHEDULETYPE" VARCHAR(50) NOT NULL , 
                  "BATCHNO" VARCHAR(20) NOT NULL , 
                  "HEADJOBNAME" VARCHAR(50) , 
                  "HEADJOBTYPE" VARCHAR(20) , 
                  "HEAD_ON_FAIL_ACTION" VARCHAR(10) , 
                  "HEADJOBSTATUS" INTEGER , 
                  "TAILJOBNAME" VARCHAR(50) , 
                  "TAILJOBTYPE" VARCHAR(20) , 
                  "TAIL_ON_FAIL_ACTION" VARCHAR(10) , 
                  "MENO" VARCHAR(128) , 
                  "PARAMS" VARCHAR(1000) , 
                  "INSERTTIME" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
                  "UPDATETIME" TIMESTAMP )   
                 IN "DWSPACE" INDEX IN "DWIDXSPACE" ; 

-- DDL Statements for indexes on Table "DBO"."JOBWAITINGPOOL"

CREATE INDEX "DBO"."IDX1_JOBWAITINGPOOL" ON "DBO"."JOBWAITINGPOOL" 
                ("SCHEDULETYPE" ASC,
                 "BATCHNO" ASC,
                 "HEADJOBNAME" ASC,
                 "TAILJOBNAME" ASC)
                ALLOW REVERSE SCANS;

                
CREATE TABLE "DBO"."JOBRUNLOG"  (
                  "ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
                    START WITH +1  
                    INCREMENT BY +1  
                    MINVALUE +1  
                    MAXVALUE +2147483647  
                    NO CYCLE  
                    CACHE 20  
                    NO ORDER ) , 
                  "SCHEDULETYPE" VARCHAR(50) NOT NULL , 
                  "BATCHNO" VARCHAR(20) NOT NULL , 
                  "JOBTYPE" VARCHAR(20) , 
                  "JOBNAME" VARCHAR(50) , 
                  "STARTTIME" TIMESTAMP , 
                  "ENDTIME" TIMESTAMP , 
                  "ELAPSEDTIME" TIME , 
                  "JOBSTATUS" INTEGER , 
                  "JOBSTATUSSTR" VARCHAR(50) , 
                  "INSERTTIME" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
                  "UPDATETIME" TIMESTAMP , 
                  "QUEUETIME" TIMESTAMP )   
                 IN "DWSPACE" INDEX IN "DWIDXSPACE" ; 






-- DDL Statements for indexes on Table "DBO"."JOBRUNLOG"

CREATE INDEX "DBO"."IDX1_JOBRUNLOG" ON "DBO"."JOBRUNLOG" 
                ("SCHEDULETYPE" ASC,
                 "BATCHNO" ASC,
                 "JOBNAME" ASC,
                 "JOBSTATUS" ASC)
                ALLOW REVERSE SCANS;

                
                
                
CREATE TABLE "DBO"."JOBSCHEDULE"  (
                  "ID" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (  
                    START WITH +1  
                    INCREMENT BY +1  
                    MINVALUE +1  
                    MAXVALUE +2147483647  
                    NO CYCLE  
                    CACHE 20  
                    NO ORDER ) , 
                  "SCHEDULETYPE" VARCHAR(50) NOT NULL , 
                  "HEADJOBNAME" VARCHAR(50) NOT NULL , 
                  "TAILJOBNAME" VARCHAR(50) NOT NULL , 
                  "BREAKOFF" INTEGER , 
                  "MEMO" VARCHAR(128) , 
                  "INSERTTIME" TIMESTAMP WITH DEFAULT CURRENT TIMESTAMP , 
                  "UPDATETIME" TIMESTAMP )   
                 IN "DWSPACE" INDEX IN "DWIDXSPACE" ; 


-- DDL Statements for primary key on Table "DBO"."JOBSCHEDULE"

ALTER TABLE "DBO"."JOBSCHEDULE" 
        ADD PRIMARY KEY
                ("SCHEDULETYPE",
                 "HEADJOBNAME",
                 "TAILJOBNAME");